project_root: /mnt/Mira/codebox
template:
  js: ""
  css: ""
  html: ""

code_processors:
  - target: js
    name: tsx

  - target: css
    name: scss

git:
  author:
    name: CodeBox
    email: automated@codebox.hub
