project_root: projects

template:
  raw: "{html_code}"
  std: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>Project Composed</title>
        {cdn_links}
      </head>
      <body>
        {html_code}
        <style>
          {css_code}
        </style>
        <script>
          {js_code}
        </script>
      </body>
    </html>

code:
  js: ""
  css: ""
  html: ""
  cdn: ""

code_processors:
  - target: html
    plugins:
        - name: Slim
        - name: Haml
        - name: Jade

  - target: css
    plugins:
       - name: Sass

  - target: js
    plugins:
    - name: React (Babel/jsx)

cdn_links:
  - name: Tailwind
    description: Tailwind classes will be usable in HTML
    type: script
    url: https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4

git:
  author:
    name: CodeBox
    email: automated@codebox.hub
