project_root: /mnt/Mira/codebox
template:
  js: |
    // JS
  css: |
    /* CSS */
  html: |
    <div>Hello World</div>

code_processors:
  - target: js
    name: babel
  - target: css
    name: scss

git:
  author:
    name: CodeBox
    email: automated@codebox.hub
