project_root: /mnt/Mira/codebox

template:
  raw: "{html_code}"
  std: |
    <!DOCTYPE html>
    <html>
        <head>
            {cdn_links}
        </head>
        <body>
            {html_code}
            <style>
                {css_code}
            </style>
            <script>
                {js_code}
            </script>
        </body>
    </html>

code:
  js: ""
  css: ""
  html: ""
  cdn: ""

code_processors:
  - target: js
    name: tsx

  - target: css
    name: scss

cdn_links:
  - name: Tailwind
    type: script
    url: https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4
  - name: React
    type: script
    url: https://cdn.jsdelivr.net/npm/react@19.2.0/jsx-runtime.min.js

git:
  author:
    name: CodeBox
    email: automated@codebox.hub
